// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: vm.proto

package vm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"` // 用户邮箱
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                          // 用户token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMReq) Reset() {
	*x = CreateVMReq{}
	mi := &file_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMReq) ProtoMessage() {}

func (x *CreateVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMReq.ProtoReflect.Descriptor instead.
func (*CreateVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVMReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CreateVMReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResp) Reset() {
	*x = CreateVMResp{}
	mi := &file_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResp) ProtoMessage() {}

func (x *CreateVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResp.ProtoReflect.Descriptor instead.
func (*CreateVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVMResp) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DestroyVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMReq) Reset() {
	*x = DestroyVMReq{}
	mi := &file_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMReq) ProtoMessage() {}

func (x *DestroyVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMReq.ProtoReflect.Descriptor instead.
func (*DestroyVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyVMReq) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DestroyVMReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type DestroyVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMResp) Reset() {
	*x = DestroyVMResp{}
	mi := &file_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMResp) ProtoMessage() {}

func (x *DestroyVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMResp.ProtoReflect.Descriptor instead.
func (*DestroyVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyVMResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RenewVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Days          int32                  `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewVMReq) Reset() {
	*x = RenewVMReq{}
	mi := &file_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewVMReq) ProtoMessage() {}

func (x *RenewVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewVMReq.ProtoReflect.Descriptor instead.
func (*RenewVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{4}
}

func (x *RenewVMReq) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RenewVMReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *RenewVMReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type RenewVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewExpiryDate string                 `protobuf:"bytes,1,opt,name=new_expiry_date,json=newExpiryDate,proto3" json:"new_expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewVMResp) Reset() {
	*x = RenewVMResp{}
	mi := &file_vm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewVMResp) ProtoMessage() {}

func (x *RenewVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewVMResp.ProtoReflect.Descriptor instead.
func (*RenewVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{5}
}

func (x *RenewVMResp) GetNewExpiryDate() string {
	if x != nil {
		return x.NewExpiryDate
	}
	return ""
}

type PowerVMReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerVMReq) Reset() {
	*x = PowerVMReq{}
	mi := &file_vm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerVMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerVMReq) ProtoMessage() {}

func (x *PowerVMReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerVMReq.ProtoReflect.Descriptor instead.
func (*PowerVMReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{6}
}

func (x *PowerVMReq) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *PowerVMReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type PowerVMResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerVMResp) Reset() {
	*x = PowerVMResp{}
	mi := &file_vm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerVMResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerVMResp) ProtoMessage() {}

func (x *PowerVMResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerVMResp.ProtoReflect.Descriptor instead.
func (*PowerVMResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{7}
}

func (x *PowerVMResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VMStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStatusReq) Reset() {
	*x = VMStatusReq{}
	mi := &file_vm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStatusReq) ProtoMessage() {}

func (x *VMStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStatusReq.ProtoReflect.Descriptor instead.
func (*VMStatusReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{8}
}

func (x *VMStatusReq) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMStatusReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type VMStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryGb      float64                `protobuf:"fixed64,6,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	PowerState    string                 `protobuf:"bytes,7,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	ToolsStatus   string                 `protobuf:"bytes,8,opt,name=tools_status,json=toolsStatus,proto3" json:"tools_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStatusResp) Reset() {
	*x = VMStatusResp{}
	mi := &file_vm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStatusResp) ProtoMessage() {}

func (x *VMStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStatusResp.ProtoReflect.Descriptor instead.
func (*VMStatusResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{9}
}

func (x *VMStatusResp) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMStatusResp) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *VMStatusResp) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *VMStatusResp) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *VMStatusResp) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *VMStatusResp) GetMemoryGb() float64 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *VMStatusResp) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

func (x *VMStatusResp) GetToolsStatus() string {
	if x != nil {
		return x.ToolsStatus
	}
	return ""
}

type ListUserVMsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserVMsReq) Reset() {
	*x = ListUserVMsReq{}
	mi := &file_vm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserVMsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserVMsReq) ProtoMessage() {}

func (x *ListUserVMsReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserVMsReq.ProtoReflect.Descriptor instead.
func (*ListUserVMsReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserVMsReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type ListAllVMsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminEmail    string                 `protobuf:"bytes,1,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"` // 验证管理员权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllVMsReq) Reset() {
	*x = ListAllVMsReq{}
	mi := &file_vm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllVMsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllVMsReq) ProtoMessage() {}

func (x *ListAllVMsReq) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllVMsReq.ProtoReflect.Descriptor instead.
func (*ListAllVMsReq) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{11}
}

func (x *ListAllVMsReq) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryGb      float64                `protobuf:"fixed64,6,opt,name=memory_gb,json=memoryGb,proto3" json:"memory_gb,omitempty"`
	PowerState    string                 `protobuf:"bytes,7,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	UserEmail     string                 `protobuf:"bytes,8,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"` // 所属用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_vm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{12}
}

func (x *VMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMInfo) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *VMInfo) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *VMInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *VMInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *VMInfo) GetMemoryGb() float64 {
	if x != nil {
		return x.MemoryGb
	}
	return 0
}

func (x *VMInfo) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

func (x *VMInfo) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type ListVMsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResp) Reset() {
	*x = ListVMsResp{}
	mi := &file_vm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResp) ProtoMessage() {}

func (x *ListVMsResp) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResp.ProtoReflect.Descriptor instead.
func (*ListVMsResp) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{13}
}

func (x *ListVMsResp) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

var File_vm_proto protoreflect.FileDescriptor

var file_vm_proto_rawDesc = string([]byte{
	0x0a, 0x08, 0x76, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x6d, 0x22, 0x42,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x23, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x29, 0x0a, 0x0d, 0x44,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x54, 0x0a, 0x0a, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x56,
	0x4d, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x79, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x22, 0x35, 0x0a, 0x0b,
	0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0f, 0x6e,
	0x65, 0x77, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d, 0x52, 0x65,
	0x71, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x27, 0x0a, 0x0b, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x41,
	0x0a, 0x0b, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x13, 0x0a,
	0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0xf2, 0x01, 0x0a, 0x0c, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6d, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x73, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x70, 0x75,
	0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f,
	0x67, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x47, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6f, 0x6c, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x56, 0x4d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x30, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x56, 0x4d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xe8, 0x01, 0x0a, 0x06, 0x56, 0x4d,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x0a, 0x05, 0x76, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6d, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70,
	0x75, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x67, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x47, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x77, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2b, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x4d, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x03, 0x76, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x76, 0x6d, 0x2e, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x76, 0x6d,
	0x73, 0x32, 0xe7, 0x02, 0x0a, 0x09, 0x56, 0x4d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x2f, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x12, 0x0f, 0x2e, 0x76, 0x6d,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x76,
	0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x12, 0x10, 0x2e,
	0x76, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x76, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x4d, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x12,
	0x0e, 0x2e, 0x76, 0x6d, 0x2e, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a,
	0x0f, 0x2e, 0x76, 0x6d, 0x2e, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4f, 0x6e, 0x56, 0x4d, 0x12,
	0x0e, 0x2e, 0x76, 0x6d, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x1a,
	0x0f, 0x2e, 0x76, 0x6d, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x56, 0x4d,
	0x12, 0x0e, 0x2e, 0x76, 0x6d, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x76, 0x6d, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x56, 0x4d, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0f, 0x2e, 0x76, 0x6d, 0x2e, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x76, 0x6d, 0x2e, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x56, 0x4d, 0x73, 0x12, 0x11, 0x2e, 0x76, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x56, 0x4d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x76, 0x6d, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x56, 0x4d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x76, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_vm_proto_rawDescOnce sync.Once
	file_vm_proto_rawDescData []byte
)

func file_vm_proto_rawDescGZIP() []byte {
	file_vm_proto_rawDescOnce.Do(func() {
		file_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)))
	})
	return file_vm_proto_rawDescData
}

var file_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_vm_proto_goTypes = []any{
	(*CreateVMReq)(nil),    // 0: vm.CreateVMReq
	(*CreateVMResp)(nil),   // 1: vm.CreateVMResp
	(*DestroyVMReq)(nil),   // 2: vm.DestroyVMReq
	(*DestroyVMResp)(nil),  // 3: vm.DestroyVMResp
	(*RenewVMReq)(nil),     // 4: vm.RenewVMReq
	(*RenewVMResp)(nil),    // 5: vm.RenewVMResp
	(*PowerVMReq)(nil),     // 6: vm.PowerVMReq
	(*PowerVMResp)(nil),    // 7: vm.PowerVMResp
	(*VMStatusReq)(nil),    // 8: vm.VMStatusReq
	(*VMStatusResp)(nil),   // 9: vm.VMStatusResp
	(*ListUserVMsReq)(nil), // 10: vm.ListUserVMsReq
	(*ListAllVMsReq)(nil),  // 11: vm.ListAllVMsReq
	(*VMInfo)(nil),         // 12: vm.VMInfo
	(*ListVMsResp)(nil),    // 13: vm.ListVMsResp
}
var file_vm_proto_depIdxs = []int32{
	12, // 0: vm.ListVMsResp.vms:type_name -> vm.VMInfo
	0,  // 1: vm.VMManager.CreateVM:input_type -> vm.CreateVMReq
	2,  // 2: vm.VMManager.DestroyVM:input_type -> vm.DestroyVMReq
	4,  // 3: vm.VMManager.RenewVM:input_type -> vm.RenewVMReq
	6,  // 4: vm.VMManager.PowerOnVM:input_type -> vm.PowerVMReq
	6,  // 5: vm.VMManager.PowerOffVM:input_type -> vm.PowerVMReq
	8,  // 6: vm.VMManager.GetVMStatus:input_type -> vm.VMStatusReq
	11, // 7: vm.VMManager.ListAllVMs:input_type -> vm.ListAllVMsReq
	1,  // 8: vm.VMManager.CreateVM:output_type -> vm.CreateVMResp
	3,  // 9: vm.VMManager.DestroyVM:output_type -> vm.DestroyVMResp
	5,  // 10: vm.VMManager.RenewVM:output_type -> vm.RenewVMResp
	7,  // 11: vm.VMManager.PowerOnVM:output_type -> vm.PowerVMResp
	7,  // 12: vm.VMManager.PowerOffVM:output_type -> vm.PowerVMResp
	9,  // 13: vm.VMManager.GetVMStatus:output_type -> vm.VMStatusResp
	13, // 14: vm.VMManager.ListAllVMs:output_type -> vm.ListVMsResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_vm_proto_init() }
func file_vm_proto_init() {
	if File_vm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vm_proto_goTypes,
		DependencyIndexes: file_vm_proto_depIdxs,
		MessageInfos:      file_vm_proto_msgTypes,
	}.Build()
	File_vm_proto = out.File
	file_vm_proto_goTypes = nil
	file_vm_proto_depIdxs = nil
}
