syntax = "proto3";

package vm_manager;

service VMManager {
  rpc CreateVM (CreateVMReq) returns (CreateVMResp) {} // 创建VM
  rpc DestroyVM (DestroyVMReq) returns (DestroyVMResp) {} // 销毁VM
  rpc RenewVM (RenewVMReq) returns (RenewVMResp) {} // 续订VM
}

message CreateVMReq {
  string user_email = 1;
}

message CreateVMResp {
  string vm_id = 1;
}

message DestroyVMReq {
  string vm_id = 1;
}

message DestroyVMResp {
  bool success = 1;
}

message RenewVMReq {
  string vm_id = 1;
}

message RenewVMResp {
  string new_expiry_date = 1;
}
